language: node_js
sudo: false
node_js:
- '6'
deploy:
  provider: npm
  email: me@platane.me
  api_key:
    secure: gf0edkkH6u3zzVY83ZbvSn7ODFWRmLN4KfQ0xgm8MoRtWTPNDuXAH+lDWx6F71BfEVSZHfCQepabZWJ6Tc6UpLwJgQB0UDUkLHCmpLgCi3+zdN44/YOUR+LGzHvHpL+hy7ZfQK6DwE14ggZ4l856hlgyOYvWKR0gIC4x5jfGerDlidIfAMG6ro4j4iiMs7AmJP32mQLf+239RWEPpn6Vid57MgXq0beOp53FJK3UiSFTn+rwOecJnvK7C+z+U3cc4eReEJbwdg3nBoIc03nC+ygrlv5gSFrSV3mOpmBecr8WdOmX8OLCuY3cNwUM5rgZwipxssdl74Bh5lJdmlzF4mo01ZUgCm++MYwe8CnSrIwmkgtKVDWzXWaHLKnoBIWnH8RKMlq+Sn0/OjQki98dlm14o6EhjilwGsJalUCcU52xbherJWsetAws3GJj9trl2mW7aIgM3nrVPgaI4Wte9KEO6JfblmwyEWPhzw8MX9ilAtCMlzNkXE4122fMJ0CM0FiLgiR/aAc8p3eMAqms2UxN8xFkNFZOIFUFjqGRUlo7Govzhe+kmLmlr56JwmPPbsdHVLqOmYBmafIyXvVby6MvN9LrJ8BAl4n6ordMLHXec+mmtb0UoWLOn5LcE2w48WYUgWlt52lZLmn+TqPwmRA5AqyMtTtDRRB13ne4J6Q=
  on:
    branch: master
    repo: Platane/refinery
  skip_cleanup: true
